version: '3.1'

services:
  postgres_one:
    container_name: postgres_one
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: bank_one
      POSTGRES_PASSWORD: bank_one
      POSTGRES_DB: bank_one_db
    ports:
      - '5432:5432'
  postgres_two:
    container_name: postgres_two
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: bank_two
      POSTGRES_PASSWORD: bank_two
      POSTGRES_DB: bank_two_db
    ports:
      - '5433:5432'
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3
    ports:
      - '9093:9093'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kowl:
    container_name: kowl
    image: quay.io/cloudhut/kowl:master
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - '8080:8080'
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

